add logic for adding dynamic another input field
Mintbase/mintbase-ui pull request #477
Opened 2023-05-25 13:22 UTC by Jxnis

changes default amount to 1 input field if nothing else gets send to component and then adds logic for adding up another input field after the previous one got filled using debounce func on onChange

2023-05-25 13:58 UTC, sainthiago requested changes

2023-05-25 13:58 UTC, sainthiago commented on src/components/inputs/input-account/near-amount-account/NearAmountAccount.tsx
> +    console.log('I AM GETTING CALLED')
🧹

2023-05-25 14:17 UTC, Jxnis commented on src/components/inputs/input-account/near-amount-account/NearAmountAccount.tsx
> +    console.log('I AM GETTING CALLED')
upsi. updated :)

2023-05-25 14:34 UTC, sainthiago approved these changes

2023-05-26 12:28 UTC, marcelokunze approved these changes

2023-05-26 14:29 UTC, merged